In [9]:
import numpy as np 
from scipy.stats import dirichlet

In [10]:
vocabulary = ['literary', 'literature', 'authors', 'century', 'texts', 'writers', 'economic', 'critique']
doc_term = np.array([[0,0,0,4,0,0,2,5],
                    [0,0,0,0,0,0,6,11],
                    [0,0,0,3,0,0,8,0],
                    [0,0,0,2,1,0,6,16],
                    [0,1,0,5,1,0,3,13],
                    [0,0,0,0,0,0,5,6],
                    [10,3,0,4,0,1,0,0],
                    [13,1,7,0,0,5,0,0],
                    [7,3,0,4,1,8,0,0],
                    [20,14,3,0,0,0,0,0],
                    [5,6,5,0,0,10,0,0],
                    [9,7,0,2,0,1,0,0],
                    [3,5,3,0,0,6,0,0],
                    [8,13,3,1,1,3,0,0],
                    [9,3,4,0,0,6,0,0],
                    [11,7,4,0,1,6,0,0],
                    [2,3,0,1,1,1,0,0],
                    [5,2,13,0,0,5,0,0],
                    [7,3,6,1,0,11,0,0],
                    [5,9,8,2,0,4,0,0]])
K = 2
V = 8
Alpha = [1] * K
Beta = [[1] * V] * K

In [11]:
Phi = dirichlet.rvs(Beta[0], size=K, random_state=1)
Theta = dirichlet.rvs(Alpha, random_state=1)
print (Phi)
print (Theta)

[[1.76368128e-01 4.16443022e-01 3.73851146e-05 1.17668808e-01
  5.18736312e-02 3.16661272e-02 6.73677889e-02 1.38575110e-01]
 [7.83659131e-02 1.19995567e-01 8.42399284e-02 1.79208850e-01
  3.54616815e-02 3.26314563e-01 4.30543290e-03 1.72108064e-01]]
[[0.29751149 0.70248851]]


In [12]:
Z = [Alpha] * doc_term.shape[0] * Theta

In [13]:
itr = 0
while itr <= 600:
    # update Phi and Beta
    e = Beta + np.multiply(doc_term, Z.T.reshape(K, doc_term.shape[0],1)).sum(axis=1) - 1 + 1e-20
    # Beta = Beta + np.multiply(doc_term, Theta.reshape(K, 1, -1)).sum(axis=1)
    for k in range(len(e)):
        Phi[k] = dirichlet.rvs(e[k], random_state=1)

    # update Z
    temp = np.power(np.repeat(Phi.reshape(Phi.shape[0], -1, Phi.shape[1]), doc_term.shape[0], axis=1), doc_term)
    temp = np.prod(temp,axis=2)
    Z = np.multiply(temp, Z.T).T
    Z = Z/Z.sum(axis=1,keepdims=True)

    # update Theta and Alpha
    d = Alpha + Z.sum(axis=0, keepdims=True)
    Theta = dirichlet.rvs(d[0], random_state=1)

    itr += 1

In [14]:
Phi

array([[3.91612389e-01, 2.17854794e-01, 1.53873394e-01, 3.24544311e-02,
        2.41278216e-02, 1.80077170e-01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.14528652e-06, 0.00000000e+00, 9.98518312e-02,
        3.13639104e-03, 0.00000000e+00, 2.52576430e-01, 6.44434202e-01]])

In [15]:
Z

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [16]:
Theta

array([[0.80721067, 0.19278933]])