In [1]:
import numpy as np 
from scipy.stats import dirichlet

In [2]:
vocabulary = ['literary', 'literature', 'authors', 'century', 'texts', 'writers', 'economic', 'critique']
doc_term = np.array([[0,0,0,4,0,0,2,5],
                    [0,0,0,0,0,0,6,11],
                    [0,0,0,3,0,0,8,0],
                    [0,0,0,2,1,0,6,16],
                    [0,1,0,5,1,0,3,13],
                    [0,0,0,0,0,0,5,6],
                    [10,3,0,4,0,1,0,0],
                    [13,1,7,0,0,5,0,0],
                    [7,3,0,4,1,8,0,0],
                    [20,14,3,0,0,0,0,0],
                    [5,6,5,0,0,10,0,0],
                    [9,7,0,2,0,1,0,0],
                    [3,5,3,0,0,6,0,0],
                    [8,13,3,1,1,3,0,0],
                    [9,3,4,0,0,6,0,0],
                    [11,7,4,0,1,6,0,0],
                    [2,3,0,1,1,1,0,0],
                    [5,2,13,0,0,5,0,0],
                    [7,3,6,1,0,11,0,0],
                    [5,9,8,2,0,4,0,0]])
K = 2
V = 8
# Alpha = [1] * K
# Beta = [[1] * V] * K
Alpha = 1
Beta = 1

In [3]:
Phi = dirichlet.rvs([Beta]*V, size=K, random_state=None)
Theta = dirichlet.rvs([Alpha]*K, random_state=None)
print (Phi)
print (Theta)

[[0.24644959 0.01630791 0.25671716 0.09999197 0.01554581 0.19262006
  0.1169087  0.05545879]
 [0.34503261 0.16612806 0.20782645 0.14784465 0.01889698 0.00302211
  0.0180343  0.09321484]]
[[0.12431366 0.87568634]]


In [4]:
Z = [[Alpha]*K] * doc_term.shape[0] * Theta

In [5]:
itr = 0
while itr <= 10:
    # update Phi and Beta
    e = Beta + np.multiply(doc_term, Z.T.reshape(K, doc_term.shape[0],1)).sum(axis=1) - 1 + 1e-20
    # Beta = Beta + np.multiply(doc_term, Theta.reshape(K, 1, -1)).sum(axis=1)
    for k in range(len(e)):
        Phi[k] = dirichlet.rvs(e[k], random_state=None)

    # update Z
    temp = np.power(np.repeat(Phi.reshape(Phi.shape[0], -1, Phi.shape[1]), doc_term.shape[0], axis=1), doc_term)
    temp = np.prod(temp,axis=2)
    Z = np.multiply(temp, Z.T).T
    Z = Z/Z.sum(axis=1,keepdims=True)

    # update Theta
    d = Alpha + Z.sum(axis=0, keepdims=True)
    Theta = dirichlet.rvs(d[0], random_state=None)
    
    itr += 1

[[9.31433225e-04 9.99068567e-01]
 [4.15176113e-02 9.58482389e-01]
 [9.66363881e-03 9.90336361e-01]
 [1.47398484e-03 9.98526015e-01]
 [1.05391747e-04 9.99894608e-01]
 [7.86529401e-02 9.21347060e-01]
 [2.63402512e-02 9.73659749e-01]
 [2.79445355e-02 9.72055464e-01]
 [1.29688121e-04 9.99870312e-01]
 [9.99629428e-01 3.70572456e-04]
 [4.24087086e-03 9.95759129e-01]
 [5.68048998e-01 4.31951002e-01]
 [3.22321142e-02 9.67767886e-01]
 [8.42265668e-01 1.57734332e-01]
 [3.34013954e-02 9.66598605e-01]
 [1.81651759e-01 8.18348241e-01]
 [9.22917890e-02 9.07708211e-01]
 [2.47007978e-03 9.97529920e-01]
 [2.22402862e-04 9.99777597e-01]
 [3.85148266e-02 9.61485173e-01]]
[[1.51294923e-11 1.00000000e+00]
 [2.25198545e-19 1.00000000e+00]
 [4.07710243e-10 1.00000000e+00]
 [2.11326940e-26 1.00000000e+00]
 [1.23802935e-21 1.00000000e+00]
 [1.00462095e-12 1.00000000e+00]
 [9.75937429e-01 2.40625705e-02]
 [1.55467027e-05 9.99984453e-01]
 [1.04654091e-04 9.99895346e-01]
 [1.00000000e+00 1.45604569e-13]
 [9.85618

In [6]:
#topic words distribution
for k, p in enumerate(Phi):
    print ('topic ',k)
    for w in np.argsort(p)[::-1][:5]:
        print (vocabulary[w], p[w])
    print ()

topic  0
critique 0.5893366481969435
economic 0.2401518327946111
century 0.11379502347450494
texts 0.05611930066594969
literature 0.0005971948679905889

topic  1
literary 0.3378107392901665
literature 0.2224780808352343
authors 0.19416287511238914
writers 0.1894308418868997
century 0.04700510053792118



In [7]:
#doc topic distribution
print ('Docs Topic0 Topic1' )
for i in range(len(Z)):
    print (i, Z[i][0], Z[i][1])

Docs Topic0 Topic1
0 1.0 0.0
1 1.0 0.0
2 1.0 0.0
3 1.0 0.0
4 1.0 0.0
5 1.0 0.0
6 0.0 1.0
7 0.0 1.0
8 0.0 1.0
9 0.0 1.0
10 0.0 1.0
11 0.0 1.0
12 0.0 1.0
13 0.0 1.0
14 0.0 1.0
15 0.0 1.0
16 0.0 1.0
17 0.0 1.0
18 0.0 1.0
19 0.0 1.0
