In [1]:
import numpy as np 
from scipy.stats import dirichlet

In [2]:
vocabulary = ['literary', 'literature', 'authors', 'century', 'texts', 'writers', 'economic', 'critique']
doc_term = np.array([[0,0,0,4,0,0,2,5],
                    [0,0,0,0,0,0,6,11],
                    [0,0,0,3,0,0,8,0],
                    [0,0,0,2,1,0,6,16],
                    [0,1,0,5,1,0,3,13],
                    [0,0,0,0,0,0,5,6],
                    [10,3,0,4,0,1,0,0],
                    [13,1,7,0,0,5,0,0],
                    [7,3,0,4,1,8,0,0],
                    [20,14,3,0,0,0,0,0],
                    [5,6,5,0,0,10,0,0],
                    [9,7,0,2,0,1,0,0],
                    [3,5,3,0,0,6,0,0],
                    [8,13,3,1,1,3,0,0],
                    [9,3,4,0,0,6,0,0],
                    [11,7,4,0,1,6,0,0],
                    [2,3,0,1,1,1,0,0],
                    [5,2,13,0,0,5,0,0],
                    [7,3,6,1,0,11,0,0],
                    [5,9,8,2,0,4,0,0]])
K = 2
V = 8
Alpha = [1] * K
Beta = [[1] * V] * K

In [11]:
Phi = dirichlet.rvs(Beta[0], size=K, random_state=None)
Theta = dirichlet.rvs(Alpha, random_state=None)
print (Phi)
print (Theta)

[[0.0497942  0.08902216 0.02985343 0.16800195 0.01129531 0.1383063
  0.15290444 0.36082221]
 [0.05548266 0.19361251 0.00651928 0.23222787 0.17719214 0.08717649
  0.24595829 0.00183077]]
[[0.46843441 0.53156559]]


In [12]:
Z = [Alpha] * doc_term.shape[0] * Theta

In [13]:
itr = 0
while itr <= 600:
    # update Phi and Beta
    e = Beta + np.multiply(doc_term, Z.T.reshape(K, doc_term.shape[0],1)).sum(axis=1) - 1 + 1e-20
    # Beta = Beta + np.multiply(doc_term, Theta.reshape(K, 1, -1)).sum(axis=1)
    for k in range(len(e)):
        Phi[k] = dirichlet.rvs(e[k], random_state=None)

    # update Z
    temp = np.power(np.repeat(Phi.reshape(Phi.shape[0], -1, Phi.shape[1]), doc_term.shape[0], axis=1), doc_term)
    temp = np.prod(temp,axis=2)
    Z = np.multiply(temp, Z.T).T
    Z = Z/Z.sum(axis=1,keepdims=True)

    # update Theta and Alpha
    d = Alpha + Z.sum(axis=0, keepdims=True)
    Theta = dirichlet.rvs(d[0], random_state=None)

    itr += 1

In [14]:
Phi

array([[0.        , 0.06285754, 0.        , 0.17728083, 0.01852746,
        0.        , 0.27863429, 0.46269988],
       [0.32203296, 0.26621963, 0.12780336, 0.04455966, 0.02188656,
        0.21749783, 0.        , 0.        ]])

In [15]:
Z

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [8]:
Theta

array([[0.78377287, 0.21622713]])