In [27]:
import numpy as np 
from scipy.stats import dirichlet

In [28]:
vocabulary = ['literary', 'literature', 'authors', 'century', 'texts', 'writers', 'economic', 'critique']
doc_term = np.array([[0,0,0,4,0,0,2,5],
                    [0,0,0,0,0,0,6,11],
                    [0,0,0,3,0,0,8,0],
                    [0,0,0,2,1,0,6,16],
                    [0,1,0,5,1,0,3,13],
                    [0,0,0,0,0,0,5,6],
                    [10,3,0,4,0,1,0,0],
                    [13,1,7,0,0,5,0,0],
                    [7,3,0,4,1,8,0,0],
                    [20,14,3,0,0,0,0,0],
                    [5,6,5,0,0,10,0,0],
                    [9,7,0,2,0,1,0,0],
                    [3,5,3,0,0,6,0,0],
                    [8,13,3,1,1,3,0,0],
                    [9,3,4,0,0,6,0,0],
                    [11,7,4,0,1,6,0,0],
                    [2,3,0,1,1,1,0,0],
                    [5,2,13,0,0,5,0,0],
                    [7,3,6,1,0,11,0,0],
                    [5,9,8,2,0,4,0,0]])
K = 2
V = 8
Alpha = [1] * K
Beta = [[1] * V] * K

In [29]:
Phi = dirichlet.rvs(Beta[0], size=K, random_state=1)
Theta = dirichlet.rvs(Alpha, random_state=1)
print (Phi)
print (Theta)

[[1.76368128e-01 4.16443022e-01 3.73851146e-05 1.17668808e-01
  5.18736312e-02 3.16661272e-02 6.73677889e-02 1.38575110e-01]
 [7.83659131e-02 1.19995567e-01 8.42399284e-02 1.79208850e-01
  3.54616815e-02 3.26314563e-01 4.30543290e-03 1.72108064e-01]]
[[0.29751149 0.70248851]]


In [30]:
Z = [Alpha] * doc_term.shape[0] * Theta

In [32]:
itr = 0
while itr <= 500:
    print (Phi)
    # update Phi and Beta
    e = Beta + np.multiply(doc_term, Z.T.reshape(K, doc_term.shape[0],1)).sum(axis=1) - 1
    Beta = Beta + np.multiply(doc_term, Theta.reshape(K, 1, -1)).sum(axis=1)
    for k in range(len(e)):
        Phi[k] = dirichlet.rvs(e[k], size=K, random_state=1)[k]

    # update Z
    temp = np.power(np.repeat(Phi.reshape(Phi.shape[0], -1, Phi.shape[1]), doc_term.shape[0], axis=1), doc_term)
    temp = np.prod(temp,axis=2)
    Z = np.multiply(temp, Z.T).T
    Z = Z/Z.sum(axis=1,keepdims=True)

    # update Theta and Alpha
    Alpha = Alpha + Z.sum(axis=0, keepdims=True)
    Theta = dirichlet.rvs(Alpha[0], random_state=1)

    itr += 1

11724081]]
[[0.26654324 0.18428589 0.12882489 0.06612813 0.01454454 0.15390269
  0.07042008 0.11535054]
 [0.26482712 0.18273648 0.12906341 0.06615375 0.01337933 0.15629096
  0.07030792 0.11724104]]
[[0.26653893 0.18428623 0.12882553 0.06612918 0.0145437  0.15390372
  0.07041892 0.11535381]
 [0.26482565 0.18273934 0.12906372 0.06615476 0.01337995 0.15628896
  0.07030635 0.11724127]]
[[0.26653463 0.18428657 0.12882616 0.06613022 0.01454286 0.15390474
  0.07041776 0.11535706]
 [0.2648242  0.18274219 0.12906404 0.06615576 0.01338056 0.15628697
  0.07030479 0.1172415 ]]
[[0.26653034 0.1842869  0.1288268  0.06613126 0.01454202 0.15390576
  0.07041661 0.11536031]
 [0.26482274 0.18274504 0.12906435 0.06615676 0.01338117 0.15628498
  0.07030323 0.11724173]]
[[0.26652608 0.18428724 0.12882743 0.0661323  0.01454118 0.15390678
  0.07041546 0.11536354]
 [0.26482129 0.18274787 0.12906466 0.06615775 0.01338177 0.15628301
  0.07030168 0.11724197]]
[[0.26652183 0.18428758 0.12882805 0.06613333 0.014540

In [26]:
e

array([[704.41701771, 493.31106036, 346.03991302, 165.18855267,
         35.06516236, 414.00127852, 155.37852521, 264.14349286],
       [549.58298229, 386.68893964, 269.96008698, 153.81144733,
         30.93483764, 322.99872148, 174.62147479, 296.85650714]])

In [65]:
Z[:,0].reshape(20,1)

array([[0.07976803],
       [0.06717348],
       [0.42643863],
       [0.02057136],
       [0.01583363],
       [0.16889951],
       [0.2848792 ],
       [0.35869203],
       [0.19637417],
       [0.48005591],
       [0.14369085],
       [0.29298648],
       [0.1838633 ],
       [0.23793582],
       [0.28351011],
       [0.33389667],
       [0.30732727],
       [0.1573534 ],
       [0.14745557],
       [0.11632197]])

In [66]:
Z.T.reshape(2,20,1)

array([[[0.07976803],
        [0.06717348],
        [0.42643863],
        [0.02057136],
        [0.01583363],
        [0.16889951],
        [0.2848792 ],
        [0.35869203],
        [0.19637417],
        [0.48005591],
        [0.14369085],
        [0.29298648],
        [0.1838633 ],
        [0.23793582],
        [0.28351011],
        [0.33389667],
        [0.30732727],
        [0.1573534 ],
        [0.14745557],
        [0.11632197]],

       [[0.92023197],
        [0.93282652],
        [0.57356137],
        [0.97942864],
        [0.98416637],
        [0.83110049],
        [0.7151208 ],
        [0.64130797],
        [0.80362583],
        [0.51994409],
        [0.85630915],
        [0.70701352],
        [0.8161367 ],
        [0.76206418],
        [0.71648989],
        [0.66610333],
        [0.69267273],
        [0.8426466 ],
        [0.85254443],
        [0.88367803]]])

In [69]:
(doc_term * Z.T.reshape(2,20,1)).sum(axis=1)

array([[33.53760949, 21.37836118, 12.265394  ,  5.15504791,  1.11193891,
        14.08204897,  4.98951258,  2.6861244 ],
       [80.46239051, 58.62163882, 43.734606  , 23.84495209,  4.88806109,
        52.91795103, 25.01048742, 48.3138756 ]])

In [37]:
Z

array([[0.07976803, 0.92023197],
       [0.06717348, 0.93282652],
       [0.42643863, 0.57356137],
       [0.02057136, 0.97942864],
       [0.01583363, 0.98416637],
       [0.16889951, 0.83110049],
       [0.2848792 , 0.7151208 ],
       [0.35869203, 0.64130797],
       [0.19637417, 0.80362583],
       [0.48005591, 0.51994409],
       [0.14369085, 0.85630915],
       [0.29298648, 0.70701352],
       [0.1838633 , 0.8161367 ],
       [0.23793582, 0.76206418],
       [0.28351011, 0.71648989],
       [0.33389667, 0.66610333],
       [0.30732727, 0.69267273],
       [0.1573534 , 0.8426466 ],
       [0.14745557, 0.85254443],
       [0.11632197, 0.88367803]])

In [44]:
doc2topic=np.full([20,2],1.)
doc2topic=doc2topic*topic
doc2topic*=word_prob
doc2topic

ValueError: operands could not be broadcast together with shapes (20,2) (20,8,1) (20,2) 

In [ ]:
doc2topic[(doc2topic.sum(axis=1,keepdims=True)==0).repeat(2,axis=1)]=1